tenancy_ocid                    = "ocid1.tenancy.oc1..aaaaaaaacdxtmf5q2fy7b4okroisf2xgab2qh6keuytui6tu2vyyuznjp4hq"
user_ocid                       = "ocid1.user.oc1..aaaaaaaasojw3w2rzaapvsvd325fvphqscfs3vawxrcwry57xlpitkikkoaq"
fingerprint                     = "3c:fa:a8:3a:17:d0:98:df:bf:73:54:d3:0e:10:ce:70"
private_key_path                = "~/.oci/oci_api_key.pem"
compartment_ocid                = "ocid1.compartment.oc1..aaaaaaaaoutphpgzsufktkwtokpfnaointc3rfmhqo562qpgdt2gqzp6jofa"
region                          = "us-ashburn-1"
vcn_dns_label                   = "horizonvdivcn"
vcn_cidr                        = "10.0.0.0/16"
public_cidr                     = "10.0.100.0/24"
private_cidr                    = "10.0.200.0/24"
public_subnet_dns_label         = "public subnet-horizonvdivcn"
private_subnet_dns_label        = "private subnet-horizonvdivcn"
vmnames                         = "jenkins-new"
image_operating_system          = "Oracle Linux"
image_operating_system_version  = "8"
instance_shape                  = "VM.Standard.E2.2"
ssh_public_key                  = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdrB8IQ2eC1BEGhUlMuEX735+IllXaFhqAEkR+7YH7HYTEVXch1A19QD3xb2sJeBE2TloYFE9y+aJj6ThWkFrMCfam+vHisTENfPv3guKjo7VamAxUXJxJO1p4dXjuxX3nPH/zfUOjkMBshkDH9cskWpO91EcoGZii8deb+vcbN9nWkFe/cgfSu+68YAvYyaxFYnEQ4U2GnVfbfh9eVt0g4vpYEKwhtDoeveILdRELP61rKQIRDTSq2j7SqNutvPoetTl2ChGq8+tQLYIUA9M7Pf88LdjXSrrR7J8C9k7Pxb1uolGxah2fQ3PJn6GJ6qv29cpQxukyCGGtCEcOaHYqZJ1Jm2Sbzl1ITeZ3xutCyFjtVYDRK1lO1veLxfpSCRMfWn6UaN+f3GpY8pcS5+uye6WtzDIHWMDg4M99LrcCQXRQVwxvt7EC8yo+eLAogCr+x6dioVNq01nBL3rvd5Nqx1l7onav5mA3fddIFzVHJEbfhj+8DI/6YU4IKmw66oM= niks@Nikhils-MacBook-Pro.local"