tenancy_ocid                    = "ocid1.tenancy.oc1..aaaaaaaacdxtmf5q2fy7b4okroisf2xgab2qh6keuytui6tu2vyyuznjp4hq"
user_ocid                       = "ocid1.user.oc1..aaaaaaaasojw3w2rzaapvsvd325fvphqscfs3vawxrcwry57xlpitkikkoaq"
fingerprint                     = "3c:fa:a8:3a:17:d0:98:df:bf:73:54:d3:0e:10:ce:70"
private_key_path                = "~/.oci/oci_api_key.pem"
compartment_ocid                = "ocid1.compartment.oc1..aaaaaaaaoutphpgzsufktkwtokpfnaointc3rfmhqo562qpgdt2gqzp6jofa"
region                          = "us-ashburn-1"
vcn_dns_label                   = "horizonvdivcn"
vcn_cidr                        = "10.0.0.0/16"
public_cidr                     = "10.0.100.0/24"
private_cidr                    = "10.0.200.0/24"
public_subnet_dns_label         = "public subnet-horizonvdivcn"
private_subnet_dns_label        = "private subnet-horizonvdivcn"
vmnames                         = "jenkins-new"
image_operating_system          = "Oracle Linux"
image_operating_system_version  = "8"
instance_shape                  = "VM.Standard.E2.2"
ssh_public_key                  = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWfEOAEvN7PF1j4eNCi0Tf+AdBfI7neCVAb8Pk3bLBMijRbJ0EbOIne/Ivx+oHYZpTg+WtSEfWkJHN6Ek60yA/zcQQWASrm6D6OW0QHyxYpLpXKpPLjVDwVoub8RpmbeTefSjSYGega9ZU/W1SMwGQZyPYAUVeO+nKvlJPUNZ22zRl5LPwmuSEb45kxfZMZVnuiC6/EcMIZPJDqJ5B5Pp2m19H78wOyI1qN8PeDfJMCvzjeI9tE/w/Pbomwu/rsqoimeSmQiMPfBSduJrmvJUtSvPKr2GUqtCYMQgox2pCsGs3cNE0yNa2VmO85DVk8TRo3bbBU1+95ljqT+pw4qKsX1FU/gpXJUqEiVwCZ1NNPUsUAi7uQBnwWtuMROh6UsTfeAK8k8JY9wLPCjIRfNE4W5DEmspPNhO4Wn/4C2nU4Wf+10tJkJEYw7JLYLrTA4S0nUbkAvOyQEKolGBe67u7SQHC2X4LdfnPNKJgT2MYpyZAvNL7TlI6eUijf03hMSc= horizonvdi\administrator@cs"